name       : arm-none-eabi-binutils
version    : 2.32
release    : 3
source     :
    - https://ftp.gnu.org/gnu/binutils/binutils-2.32.tar.xz : 0ab6c55dd86a92ed561972ba15b9b70a8b9f75557f896446c82e8b36e473ee04
license    : GPL-3.0-or-later
summary    : The GNU Embedded Binutils for Arm
component  : programming
description: |
    A set of programs to assemble and manipulate binary and object files for the ARM EABI (bare-metal) target
environment: |
    export TARGET=arm-none-eabi
    export PREFIX=/usr/share/$TARGET
setup      : |
    %patch -p1 < $pkgfiles/0001-Include-string.patch
    ./configure \
        --build=%HOST% \
        --target=$TARGET \
        --prefix=$PREFIX \
        --enable-multilib \
        --enable-interwork \
        --with-gnu-as \
        --with-gnu-ld \
        --disable-nls \
        --enable-ld=default \
        --enable-gold \
        --enable-plugins \
        --enable-deterministic-archives
build      : |
    %make
install    : |
    %make_install 

    # Remove unnecessary files
    rm -rf $installdir$PREFIX/share

    # Install profile.d script which adds arm toolchain to path
    install -D -m 00644 $pkgfiles/50-arm-toolchain-path.sh $installdir/usr/share/defaults/etc/profile.d/50-arm-toolchain-path.sh
